RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\tools\convert.py", line 698, in _tag_root
    f(rec)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\tools\convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\models.py", line 4368, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\models.py", line 4290, in _load_records_create
    return self.create(values)
  File "<decorator-gen-198>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\website\models\ir_ui_view.py", line 55, in create
    return super().create(vals_list)
  File "<decorator-gen-47>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\base\models\ir_ui_view.py", line 554, in create
    result = super(View, self.with_context(ir_ui_view_partial_validation=True)).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\base\models\ir_fields.py", line 665, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\models.py", line 3902, in create
    raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'Policy Data' on model 'ir.ui.view'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\service\model.py", line 134, in retrying
    result = func()
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\http.py", line 1808, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\base\models\ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\base\models\ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\base\models\ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\addons\base\models\ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\modules\registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\modules\loading.py", line 489, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\modules\loading.py", line 373, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\modules\loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\modules\loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\tools\convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\tools\convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\tools\convert.py", line 749, in parse
    self._tag_root(de)
  File "C:\Program Files\Odoo 16.0.20221031\server\odoo\tools\convert.py", line 715, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing file:/c:/program%20files/odoo%2016.0.20221031/server/addons/gmc_module/views/gmcmodule_policytable.xml:15, somewhere inside
<record id="gmcmodule_policytable_view_form" model="ir.ui.view">
   <field name="Policy Data">Application Table Name Form</field>
   <field name="model">gmcmodule.policytable</field>
   <field name="arch" type="xml">
         <form>
 	     <group>
	        <field name="Policy Data"/>	
	     </group>
	 </form>
   </field>
</record>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/277-f0220e1/web.assets_backend.min.js:970:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/277-f0220e1/web.assets_backend.min.js:978:13)